// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBukUELqOuvBy6GHZMmF60HVNiRz5F4oLI',
    appId: '1:728734273503:web:13315efa045ad55fb6fe6a',
    messagingSenderId: '728734273503',
    projectId: 'activo-3935b',
    authDomain: 'activo-3935b.firebaseapp.com',
    storageBucket: 'activo-3935b.firebasestorage.app',
    measurementId: 'G-HQT7D2GE98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW9fgfEKD41Hze1OVOmuPJieFOTb5jf4s',
    appId: '1:728734273503:android:fb31ab659464ca36b6fe6a',
    messagingSenderId: '728734273503',
    projectId: 'activo-3935b',
    storageBucket: 'activo-3935b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR2Blqg_8K8QrYndNgDNtARbRZExnfDbI',
    appId: '1:728734273503:ios:5689e16f2fc58eaeb6fe6a',
    messagingSenderId: '728734273503',
    projectId: 'activo-3935b',
    storageBucket: 'activo-3935b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR2Blqg_8K8QrYndNgDNtARbRZExnfDbI',
    appId: '1:728734273503:ios:5689e16f2fc58eaeb6fe6a',
    messagingSenderId: '728734273503',
    projectId: 'activo-3935b',
    storageBucket: 'activo-3935b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBukUELqOuvBy6GHZMmF60HVNiRz5F4oLI',
    appId: '1:728734273503:web:1567216ebc2784e3b6fe6a',
    messagingSenderId: '728734273503',
    projectId: 'activo-3935b',
    authDomain: 'activo-3935b.firebaseapp.com',
    storageBucket: 'activo-3935b.firebasestorage.app',
    measurementId: 'G-VFE4209LFW',
  );
}
